platform :ios, 7.0
pod 'AFNetworking', '~>  2.0.2'
pod 'iCarousel'
pod 'CocoaLumberjack'
pod 'Parse'
pod 'CocoaAsyncSocket'
pod 'XCAsyncTestCase'
pod 'REKit'
pod 'BlocksKit'
pod 'RESideMenu'
pod 'JBChartView', '~> 2.1.3'