platform :ios, 6.1
pod 'AFNetworking', '~>  2.0.2'
pod 'google-plus-ios-sdk', '~> 1.4.1'
pod 'UIAlertView+Blocks'
pod 'iCarousel'
pod 'GPUImage'
pod 'NSObject+AutoDescription'
pod 'LBBlurredImage'
pod 'CocoaLumberjack'
pod 'Parse'
